export default {
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_LARGE: 16,
    PRIMARY_COLOR: '#0A0325',
    PRIMARY_FONT_COLOR: '#FFFFFF',
    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,

    PROJECT_ONE_BG: 'red',
    PROJECT_TWO_BG: '#1B1E27',
    PROJECT_THREE_BG: 'rgb(238, 167, 2)',
  };